In [1]:
# Import the required libraries

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import warnings
from IPython.display import HTML
import seaborn as sns
import scipy.stats as stats
#import plotly.graph_objects as go
#import plotly.express as px

# Set any preferences you want for the notebook
warnings.filterwarnings('ignore')

HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Click here to toggle on/off the raw code."></form>''')

In [2]:
# Set the home directory to the main repository page

os.chdir('..')
os.listdir()

['.DS_Store', 'analysis', 'docs', 'README.md', '.git', 'data']

In [3]:
# Read in the dataset

df = pd.read_csv('data/data.csv')

In [4]:
# Create a column called 'company' which identifies where a company belongs to

df['company'] = 1

company_number = 1
for i in range(1, len(df['company'])):
    if df['Stock return'][i] == df['Stock return'][i-1]:
        df['company'][i] = company_number
    else:
        company_number = company_number + 1
        df['company'][i] = company_number

### Employee Level Correlation

In [5]:
df.corr()

,Compensation,Log(sales),Stock return,Volatility,Board size,Fraction of female,Fraction of independent,Gender,Age,Tenure,Number of other directorship,Retired,company
Compensation,1.000000,0.162819,0.215032,-0.068603,0.152201,0.062700,0.114229,0.049193,-0.062640,-0.058645,-0.048328,-0.014662,0.026114
Log(sales),0.162819,1.000000,0.054288,-0.023857,0.106983,0.035304,0.076325,0.018224,-0.011466,0.025234,-0.026219,0.025771,-0.121688
Stock return,0.215032,0.054288,1.000000,0.044127,0.043654,-0.109763,0.025261,-0.056659,0.024939,-0.033032,0.024531,0.032892,0.017552
Volatility,-0.068603,-0.023857,0.044127,1.000000,-0.063345,0.019086,0.074161,0.009852,-0.035535,0.011064,0.004166,-0.006270,-0.051532
Board size,0.152201,0.106983,0.043654,-0.063345,1.000000,0.052117,0.367382,0.026903,-0.001452,-0.022462,-0.054332,0.017596,-0.047621
Fraction of female,0.062700,0.035304,-0.109763,0.019086,0.052117,1.000000,0.050616,0.516196,-0.042869,0.018210,-0.021414,-0.001785,-0.028632
Fraction of independent,0.114229,0.076325,0.025261,0.074161,0.367382,0.050616,1.000000,0.026128,0.003162,-0.006616,-0.041554,0.040557,0.035325
Gender,0.049193,0.018224,-0.056659,0.009852,0.026903,0.516196,0.026128,1.000000,-0.006069,-0.028995,-0.009615,-0.012263,-0.014780
Age,-0.062640,-0.011466,0.024939,-0.035535,-0.001452,-0.042869,0.003162,-0.006069,1.000000,0.018058,0.029775,0.010105,-0.017206
Tenure,-0.058645,0.025234,-0.033032,0.011064,-0.022462,0.018210,-0.006616,-0.028995,0.018058,1.000000,0.023896,0.011761,-0.017517
Number of other directorship,-0.048328,-0.026219,0.024531,0.004166,-0.054332,-0.021414,-0.041554,-0.009615,0.029775,0.023896,1.000000,0.008078,0.037404
Retired,-0.014662,0.025771,0.032892,-0.006270,0.017596,-0.001785,0.040557,-0.012263,0.010105,0.011761,0.008078,1.000000,-0.000809
company,0.026114,-0.121688,0.017552,-0.051532,-0.047621,-0.028632,0.035325,-0.014780,-0.017206,-0.017517,0.037404,-0.000809,1.000000

### Company Level Correlation

In [6]:
df_cmp = df[['company', 'Log(sales)', 'Stock return', 'Volatility', 'Board size', 'Fraction of female', 'Fraction of independent']].drop_duplicates(ignore_index = True)
df_cmp.corr()

,company,Log(sales),Stock return,Volatility,Board size,Fraction of female,Fraction of independent
company,1.000000,-0.103231,0.005355,-0.036281,-0.018666,-0.004264,0.015970
Log(sales),-0.103231,1.000000,0.043957,-0.014757,0.130304,0.076692,0.117107
Stock return,0.005355,0.043957,1.000000,0.038571,0.007450,-0.088846,0.025713
Volatility,-0.036281,-0.014757,0.038571,1.000000,-0.029571,0.007620,0.067556
Board size,-0.018666,0.130304,0.007450,-0.029571,1.000000,0.131014,0.419892
Fraction of female,-0.004264,0.076692,-0.088846,0.007620,0.131014,1.000000,0.091038
Fraction of independent,0.015970,0.117107,0.025713,0.067556,0.419892,0.091038,1.000000