In [1]:
# Import the required libraries

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
import warnings
from IPython.display import HTML
import seaborn as sns
import scipy.stats as stats
#import plotly.graph_objects as go
#import plotly.express as px

# Set any preferences you want for the notebook
warnings.filterwarnings('ignore')

HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Click here to toggle on/off the raw code."></form>''')

In [2]:
# Set the home directory to the main repository page

os.chdir('..')
os.listdir()

['.DS_Store', 'analysis', 'docs', 'README.md', '.git', 'data']

In [3]:
# Read in the dataset

df = pd.read_csv('data/data.csv')

In [4]:
# Create a column called 'company' which identifies where a company belongs to

df['company'] = 1

company_number = 1
for i in range(1, len(df['company'])):
    if df['Stock return'][i] == df['Stock return'][i-1]:
        df['company'][i] = company_number
    else:
        company_number = company_number + 1
        df['company'][i] = company_number

In [5]:
df[['Compensation', 'Gender', 'Age', 'Tenure', 'Number of other directorship', 'Retired']].apply(stats.zscore)

,Compensation,Gender,Age,Tenure,Number of other directorship,Retired
0,0.167834,1.238511,-0.147210,-1.343114,-1.148748,0.992059
1,0.679363,1.238511,-0.277503,-0.143893,0.631659,0.992059
2,-0.277072,-0.807421,-0.407797,0.455718,1.521862,0.992059
3,-0.692424,-0.807421,1.416307,-0.263815,-1.148748,0.992059
4,-0.353905,-0.807421,0.373962,-0.983348,1.521862,0.992059
...,...,...,...,...,...,...
1751,0.757267,1.238511,-2.101607,0.815484,0.631659,0.992059
1752,-0.040095,1.238511,-0.407797,-0.143893,-1.148748,0.992059
1753,-0.483468,1.238511,-2.231900,0.095951,-0.258544,0.992059
1754,-1.126689,-0.807421,1.155720,0.575640,-1.148748,-1.008005
1755,-0.513765,-0.807421,1.676893,-0.383737,-1.148748,0.992059

In [6]:
df_cmp = df[['company', 'Log(sales)', 'Stock return', 'Volatility', 'Board size', 'Fraction of female', 'Fraction of independent']].drop_duplicates(ignore_index = True)
df_cmp.apply(stats.zscore)

,company,Log(sales),Stock return,Volatility,Board size,Fraction of female,Fraction of independent
0,-1.723412,1.177888,0.899967,0.631775,-0.623828,-0.396229,-0.762726
1,-1.706091,0.296612,-0.729223,0.207482,-0.623828,-0.971692,-1.408784
2,-1.688771,1.175300,1.087535,0.167679,0.778033,0.650067,-0.997656
3,-1.671450,-0.317121,-0.056901,0.856170,-0.623828,0.754696,-0.762726
4,-1.654129,0.111147,0.121642,0.147209,1.128499,-1.547155,-1.408784
...,...,...,...,...,...,...,...
195,1.654129,-1.074238,-1.128260,-0.574313,0.427568,0.869789,-0.956544
196,1.671450,-2.094128,0.654784,1.655694,0.427568,-1.144331,-0.052062
197,1.688771,-0.078352,-0.823878,-0.078316,0.077102,-1.547155,0.098685
198,1.706091,-1.276514,-0.941275,1.423536,-0.273363,-0.540095,0.287119
199,1.723412,0.646260,1.197734,0.278901,-0.273363,1.474025,-0.278182